/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Albums {
  created_at: Generated<Timestamp>;
  description: string | null;
  id: Generated<string>;
  title: string;
  user_id: string;
}

export interface Images {
  album_id: string;
  created_at: Generated<Timestamp>;
  filename: string;
  id: Generated<string>;
  mime_type: string;
  size: string;
  stored_filename: string;
  user_id: string;
}

export interface RefreshTokens {
  created_at: Generated<Timestamp>;
  expires_at: Generated<Timestamp>;
  id: Generated<string>;
  refresh_token: string;
  user_id: string;
}

export interface Roles {
  id: Generated<number>;
  name: string;
}

export interface SharedAlbums {
  album_id: string;
  id: Generated<string>;
  user_id: string;
}

export interface Users {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  password: string;
  role_id: Generated<number>;
}

export interface DB {
  albums: Albums;
  images: Images;
  refresh_tokens: RefreshTokens;
  roles: Roles;
  shared_albums: SharedAlbums;
  users: Users;
}
